{
 "title": "test",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "mem_sys_bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_sys_bytes" }
   ]
  },
  {
   "title": "cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "100-avg(rate(node_cpu_seconds_total{ mode=\"idle\"}[30s]))*100"
    }
   ]
  },
  {
   "title": "network",
   "type": "gauge",
   "description": "enternet",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_packets_total{device=\"en0\"}"
    }
   ]
  },
  {
   "title": "memory_usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "100-node_memory_free_bytes/node_memory_total_bytes*100"
    }
   ]
  },
  {
   "title": "remote_storage_samples",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_remote_storage_samples_in_total"
    }
   ]
  },
  { "type": "welcome", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 } },
  { "type": "gettingstarted", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 15, "w": 12, "x": 0, "y": 23 } },
  { "title": "Latest from the blog", "type": "news", "gridPos": { "h": 15, "w": 12, "x": 12, "y": 23 } }
 ]
}