
services:
  prometheus:
    image: ubuntu/prometheus:2.20-20.04_beta
    environment:
      - TZ=UTC
    deploy:
      mode: global
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 1024M
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  db:
    image: postgres:12.10
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  exporter:
    image: bitnami/postgres-exporter:0.10.1
    environment:
      DATA_SOURCE_NAME: postgresql://postgres:example@db:5432/postgres?sslmode=disable
#      - DATA_SOURCE_NAME="user=postgres host=/var/run/postgresql/ sslmode=disable" postgres_exporter
#      - DATA_SOURCE_NAME=postgresql://postgres_exporter:password@db:5432/postgres?sslmode=disable
    ports:
      - "9187:9187"

  grafana:
    image: grafana/grafana:8.4.4-ubuntu
    ports:
      - "3000:3000"
    user: '104'
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - grafana-logs:/var/log/grafana
    depends_on:
      - prometheus


volumes:
  grafana-data:
  grafana-config:
  grafana-logs: